name: Publish Docker Image
on:
  push:
    branches:
      - main # Adjust this if you're using a different branch

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
          docker buildx build --push \
            --tag gnizamaaa/pi_universe:latest \
            --build-arg DATABASE=social-api-db \
            --build-arg USER=${{ secrets.DB_USER }} \
            --build-arg PASSWORD=${{ secrets.DB_PASSWORD }} \
            --build-arg CLUSTER=${{ secrets.DB_CLUSTER }} \
            .
